name: nf-cmgg CI
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  build:
    name: Build nf-cmgg
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        java_version: [17, 21, 25]

    steps:
      - name: Environment
        run: env | sort

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: true

      - name: Setup Java ${{ matrix.java_version }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{matrix.java_version}}
          distribution: 'adopt'
          architecture: x64
          cache: gradle

      - name: Setup Nextflow
        uses: nf-core/setup-nextflow@b4ec1bc7c16a94435159de94a05253542fddf6ef # v3
        with:
          version: "latest-stable"

      - name: Install nf-test
        uses: nf-core/setup-nf-test@4069fbbaabe94c08faba4ad261bfa88225ba133f # v2
        with:
          version: "0.9.5"
          install-pdiff: true

      - name: Tests
        run: make test
        env:
          GRADLE_OPTS: '-Dorg.gradle.daemon=false'

      - name: Publish tests report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-jdk-${{ matrix.java_version }}
          path: |
            ./plugins/nf-cmgg/build/reports/tests/test/**